# Site settings
title: Hide Fedora
description: > # this means to ignore newlines until "baseurl:"
    Open source and free browser extension that removes annoying YouTube troll comments.
exclude: [Gemfile, Gemfile.lock, README.md]
